# Generated by Django 6.0.2 on 2026-02-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gouvernorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gouvernorat',
                'verbose_name_plural': 'Gouvernorats',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, default='')),
                ('site_web', models.URLField(blank=True, default='')),
                ('gouvernorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='orientation.gouvernorat')),
            ],
            options={
                'verbose_name': 'Université / Établissement',
                'verbose_name_plural': 'Universités / Établissements',
                'ordering': ['nom'],
                'unique_together': {('nom', 'gouvernorat')},
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code filière officiel (ex: 601, 301P, …)', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('type_diplome', models.CharField(blank=True, default='Licence', help_text='Licence, Ingénieur, Prépa, …', max_length=50)),
                ('duree_annees', models.PositiveSmallIntegerField(default=3)),
                ('sections_admises', models.CharField(blank=True, default='', help_text='Sections bac admises, séparées par des virgules (M,S,T…)', max_length=50)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='orientation.universite')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(help_text="Année d'admission (ex : 2023)")),
                ('section_bac', models.CharField(choices=[('M', 'Mathématiques'), ('S', 'Sciences Expérimentales'), ('T', 'Technique'), ('E', 'Économie et Gestion'), ('L', 'Lettres'), ('I', 'Informatique'), ('SP', 'Sport')], help_text='Section du baccalauréat', max_length=3)),
                ('score_dernier_admis', models.FloatField(help_text='Score (sur 4) du dernier admis')),
                ('score_premier_admis', models.FloatField(blank=True, help_text='Score (sur 4) du premier admis (optionnel)', null=True)),
                ('nombre_places', models.PositiveIntegerField(blank=True, help_text='Nombre de places offertes', null=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='orientation.filiere')),
            ],
            options={
                'verbose_name': 'Score historique',
                'verbose_name_plural': 'Scores historiques',
                'ordering': ['-annee', 'filiere'],
                'unique_together': {('filiere', 'annee', 'section_bac')},
            },
        ),
    ]
